services:
    vivait_generator.generator.listener:
        class: Vivait\StringGeneratorBundle\EventListener\GeneratorListener
        public: false
        arguments: ["@annotation_reader"]
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    vivait_generator.registry:
        class: Vivait\StringGeneratorBundle\Registry\Registry
        arguments: [@service_container, []]